import crypto from 'crypto';
import Anthropic from '@anthropic-ai/sdk';
import { config } from '../../config/index.js';
import { safeSet,safeGet } from '../redis.js';
import { buildRadarBaseline } from './radar.js';
import { renderEvelynJourney } from './render.js';

const client=new Anthropic({apiKey:config.anthropic.apiKey});
const fallback=(name)=>({name,opening:'Esta jornada organiza o que você compartilhou e propõe uma direção possível para os próximos 90 dias.',moment_title:'Seu ponto de partida merece ser compreendido com cuidado.',moment:'Seu momento será aprofundado sem respostas prontas e sem reduzir sua história à alimentação.',attention:'Os padrões e situações que mais dificultam seu cotidiano poderão ser explorados durante o acompanhamento.',transformations:[{today_title:'Uma rotina que exige demais',today:'Você relatou dificuldade para sustentar mudanças quando a vida real aperta.',goal_title:'Uma estrutura possível',goal:'Buscar respostas que possam continuar existindo também nos dias difíceis.'},{today_title:'Recomeços frequentes',today:'As tentativas anteriores não trouxeram a continuidade que você procura.',goal_title:'Continuidade sem perfeição',goal:'Construir uma forma de retomar sem transformar oscilações em fracasso.'},{today_title:'Decisões sob pressão',today:'Alguns momentos tornam as escolhas mais difíceis.',goal_title:'Mais recursos disponíveis',goal:'Perceber esses momentos mais cedo e ampliar suas possibilidades de resposta.'}],phases:[{period:'Início',title:'Estabelecer o ponto de partida',text:'Compreender sua história, prioridades e contexto real.'},{period:'Primeiros 30 dias',title:'Reconhecer',text:'Observar situações e automatismos sem julgamento.'},{period:'30–60 dias',title:'Experimentar',text:'Testar novas respostas e ajustar o processo com o que surgir na vida real.'},{period:'60–90 dias',title:'Consolidar',text:'Fortalecer autonomia e preparar continuidade.'}],why_evelyn:'Você expressou o desejo de ser acompanhada diretamente pela criadora da metodologia, e esta modalidade oferece a proximidade e a consistência semanal que procura.',evelyn_fit:'A proposta não parte de gravidade ou hierarquia clínica. Parte do formato de acompanhamento que você manifestou desejar.',lia_intro:'Entre os encontros, a LIA ajuda a registrar acontecimentos, organizar reflexões e aplicar intervenções elegíveis da metodologia.',community:'Durante o acompanhamento, você também faz parte do ecossistema Table, com acesso a encontros, experiências e iniciativas online e presenciais conforme calendário.',no_repeat:['Depender de fazer tudo perfeitamente.','Esperar a próxima semana para começar novamente.'],no_repeat_closing:'A direção é construir algo que continue possível quando a vida real acontecer.'});

function evidencePayload(leadData,history){return {name:leadData.nome||leadData.name||'você',source:leadData.source||null,form:{main_weight:leadData.oqueMaisPesa||leadData.dores||null,main_difficulty:leadData.maiorDificuldade||leadData.dificuldade||null,history:leadData.historico||null,health:leadData.saude||null,commitment:leadData.comprometimento||null,answers:leadData.respostas||null},conversation:history.filter(x=>x.role==='user').slice(-16).map((x,i)=>({ref:`conversation:${i+1}`,text:String(x.content).slice(0,700)}))};}

export async function createEvelynJourney({phone,leadData,history}){
 const evidence=evidencePayload(leadData,history);const baseline=buildRadarBaseline(evidence,'sdr_context');
 const system=`Você organiza uma Jornada Evelyn comercial e personalizada. Use somente fatos do JSON. Não diagnostique, não atribua causas, não explique fisiologia, não afirme por que tratamentos falharam, não prometa resultado e nunca diga que Evelyn já avaliou o caso. Escreva em português brasileiro natural, sem travessão. A transformação é direção, não garantia. Não venda quantidade de consultas nem tecnologia. Retorne JSON estrito com: name, opening, moment_title, moment, attention, transformations (3 objetos: today_title,today,goal_title,goal), phases (4 objetos: period,title,text), why_evelyn, evelyn_fit, lia_intro, community, no_repeat (0 a 4 strings relacionadas apenas ao relato), no_repeat_closing. why_evelyn deve falar de fit e intenção explícita, sem desvalorizar a equipe Table. LIA apenas registra contexto, organiza reflexões e entrega intervenções elegíveis pelo WhatsApp; Evelyn conduz.`;
 const response=await client.messages.create({model:'claude-sonnet-4-5',max_tokens:2600,system,messages:[{role:'user',content:JSON.stringify(evidence)}]});
 let data;try{data=JSON.parse(response.content[0].text.replace(/```json|```/g,'').trim())}catch{data=fallback(evidence.name)}
 const slug=`evelyn-${crypto.randomUUID()}`;const html=renderEvelynJourney({slug,data,baseline,price:config.evelyn.price,checkoutUrl:config.evelyn.checkoutUrl});
 const meta={phone,leadData,baseline,objective_90_days:data.transformations,generatedAt:new Date().toISOString(),model:'claude-sonnet-4-5',criteriaVersion:baseline.version};
 await safeSet(`evelyn_html:${slug}`,html,'EX',60*60*24*90);await safeSet(`evelyn_meta:${slug}`,JSON.stringify(meta),'EX',60*60*24*90);
 return {slug,url:`${config.evelyn.journeyBaseUrl.replace(/\/$/,'')}/evelyn/${slug}`,baseline,objective90Days:data.transformations};
}
export async function getEvelynJourney(slug){return safeGet(`evelyn_html:${slug}`)}
export async function getEvelynJourneyMeta(slug){const raw=await safeGet(`evelyn_meta:${slug}`);try{return raw?JSON.parse(raw):null}catch{return null}}
